
import { msalInstance, ensureSignedIn, login, logout, getRole } from './msal-init.js';
import { resolveSiteAndLists, getTopProjects, createOrUpdateProject, deleteProject, getTasks, createOrUpdateTask, deleteTask, uploadTaskPhotos } from './graph-client.js';
let ctx = { siteId:null, projectListId:null, taskListId:null, role:'viewer', projects:[], tasks:[] };
const debounce = (fn, ms=600) => { let t; return (...args) => { clearTimeout(t); t = setTimeout(()=>fn(...args), ms); }; };
function showSignedOut() { document.getElementById('appMain').classList.add('hidden'); document.getElementById('signedOutMain').classList.remove('hidden'); document.getElementById('btnSignIn').classList.remove('hidden'); document.getElementById('btnSignOut').classList.add('hidden'); document.getElementById('userEmail').textContent = ''; }
function showSignedIn(account) { document.getElementById('signedOutMain').classList.add('hidden'); document.getElementById('appMain').classList.remove('hidden'); document.getElementById('btnSignIn').classList.add('hidden'); document.getElementById('btnSignOut').classList.remove('hidden'); document.getElementById('userEmail').textContent = account.username || account.name || ''; }
function applyRBAC() { ctx.role = getRole(); document.querySelectorAll('.rbac-admin').forEach(el => { el.style.display = (ctx.role === 'admin') ? '' : 'none'; const input = el.querySelector('input,textarea,select'); if (input) input.disabled = (ctx.role !== 'admin'); }); document.querySelectorAll('.rbac-not-viewer').forEach(el => { el.style.display = (ctx.role === 'viewer') ? 'none' : ''; }); }
async function boot() { const ids = await resolveSiteAndLists(); ctx.siteId = ids.siteId; ctx.projectListId = ids.projectListId; ctx.taskListId = ids.taskListId; applyRBAC(); await loadProjectsTop8(); await loadTasks(); wireEditors(); }
function wireEditors() { document.getElementById('btnAddProject').onclick = () => openProjectModal(); document.getElementById('btnAddTask').onclick = () => openTaskModal(); document.getElementById('btnCloseProject').onclick = () => document.getElementById('projectModal').close(); document.getElementById('btnCloseTask').onclick = () => document.getElementById('taskModal').close(); const projectForm = document.getElementById('projectForm'); projectForm.oninput = debounce(async () => { const fields = collectProjectFields(); const itemId = projectForm.dataset.itemId || null; const resp = await createOrUpdateProject(ctx.siteId, ctx.projectListId, itemId, fields); if (!itemId) projectForm.dataset.itemId = resp.id; await loadProjectsTop8(); }, 900); projectForm.onsubmit = async (e) => { e.preventDefault(); const fields = collectProjectFields(); const itemId = projectForm.dataset.itemId || null; await createOrUpdateProject(ctx.siteId, ctx.projectListId, itemId, fields); await loadProjectsTop8(); document.getElementById('projectModal').close(); }; document.getElementById('btnDeleteProject').onclick = async () => { if (ctx.role !== 'admin') return; const itemId = projectForm.dataset.itemId; if (itemId) { await deleteProject(ctx.siteId, ctx.projectListId, itemId); await loadProjectsTop8(); document.getElementById('projectModal').close(); } }; const taskForm = document.getElementById('taskForm'); taskForm.onsubmit = async (e) => { e.preventDefault(); const fields = collectTaskFields(); const itemId = taskForm.dataset.itemId || null; await createOrUpdateTask(ctx.siteId, ctx.taskListId, itemId, fields); const files = Array.from(document.getElementById('taskPhotos').files || []); if (files.length) await uploadTaskPhotos(ctx.siteId, files); await loadTasks(); document.getElementById('taskModal').close(); }; document.getElementById('btnDeleteTask').onclick = async () => { if (ctx.role !== 'admin') return; const itemId = taskForm.dataset.itemId; if (itemId) { await deleteTask(ctx.siteId, ctx.taskListId, itemId); await loadTasks(); document.getElementById('taskModal').close(); } }; }
async function loadProjectsTop8() { const data = await getTopProjects(ctx.siteId, ctx.projectListId, 8); ctx.projects = data.value || []; const tbody = document.querySelector('#projectTable tbody'); tbody.innerHTML = ''; for (const it of ctx.projects) { const f = it.fields || {}; const tr = document.createElement('tr'); tr.innerHTML = `
      <td>${escapeHtml(f.Title || '')}</td>
      <td>${escapeHtml(f.Owner || '')}</td>
      <td>${escapeHtml((f.StartDate||'').split('T')[0])}</td>
      <td>${escapeHtml(f.ExpectedSales || '')}</td>
      <td>${f.Active ? '✔' : ''}</td>
      <td>
        ${ctx.role === 'viewer' ? '' : `<button class='btn-edit'>Edit</button>`}
        ${ctx.role === 'admin' ? `<button class='btn-del'>Delete</button>` : ''}
      </td>`; if (ctx.role !== 'viewer') tr.querySelector('.btn-edit').onclick = () => openProjectModal(it); if (ctx.role === 'admin') tr.querySelector('.btn-del').onclick = async () => { await deleteProject(ctx.siteId, ctx.projectListId, it.id); await loadProjectsTop8(); }; tbody.appendChild(tr); } document.getElementById('statTotalProjects').textContent = ctx.projects.length; document.getElementById('statActiveProjects').textContent = ctx.projects.filter(p => p.fields?.Active).length; }
async function loadTasks() { const data = await getTasks(ctx.siteId, ctx.taskListId); ctx.tasks = data.value || []; const tbody = document.querySelector('#taskTable tbody'); tbody.innerHTML = ''; for (const it of ctx.tasks) { const f = it.fields || {}; const tr = document.createElement('tr'); tr.innerHTML = `
      <td>${escapeHtml(f.Title || '')}</td>
      <td>${escapeHtml(f.Address || '')}</td>
      <td>${escapeHtml((f.StartDate||'').split('T')[0])}</td>
      <td>${escapeHtml((f.EndDate||'').split('T')[0])}</td>
      <td>${escapeHtml(f.Quantity || '')}</td>
      <td>${escapeHtml(f.UnitCost || '')}</td>
      <td>${escapeHtml(f.TotalCost || '')}</td>
      <td>${escapeHtml(f.Allocation || '')}</td>
      <td>${escapeHtml(f.Sprint || '')}</td>
      <td>${escapeHtml(f.Assignee || '')}</td>
      <td>
        ${ctx.role === 'viewer' ? '' : `<button class='btn-edit'>Edit</button>`}
        ${ctx.role === 'admin' ? `<button class='btn-del'>Delete</button>` : ''}
      </td>`; if (ctx.role !== 'viewer') tr.querySelector('.btn-edit').onclick = () => openTaskModal(it); if (ctx.role === 'admin') tr.querySelector('.btn-del').onclick = async () => { await deleteTask(ctx.siteId, ctx.taskListId, it.id); await loadTasks(); }; tbody.appendChild(tr); } }
function openProjectModal(item=null) { const dlg = document.getElementById('projectModal'); const form = document.getElementById('projectForm'); form.reset(); form.dataset.itemId = ''; if (item) { const f = item.fields || {}; form.Title.value = f.Title||''; form.Owner.value = f.Owner||''; form.StartDate.value = (f.StartDate||'').split('T')[0]; form.ExpectedSales.value = f.ExpectedSales||''; form.Active.checked = !!f.Active; form.dataset.itemId = item.id; } dlg.showModal(); }
function openTaskModal(item=null) { const dlg = document.getElementById('taskModal'); const form = document.getElementById('taskForm'); form.reset(); form.dataset.itemId = ''; document.getElementById('taskPhotos').value = ''; if (item) { const f = item.fields || {}; form.Title.value = f.Title||''; form.Address.value = f.Address||''; form.StartDate.value = (f.StartDate||'').split('T')[0]; form.EndDate.value = (f.EndDate||'').split('T')[0]; form.Quantity.value = f.Quantity||''; form.UnitCost.value = f.UnitCost||''; form.TotalCost.value = f.TotalCost||''; form.Allocation.value = f.Allocation||''; form.Sprint.value = f.Sprint||''; form.Assignee.value = f.Assignee||''; form.Description.value = f.Description||''; form.Notes.value = f.Notes||''; form.dataset.itemId = item.id; } dlg.showModal(); }
function collectProjectFields() { const f = document.getElementById('projectForm'); return { Title: f.Title.value.trim(), Owner: f.Owner.value.trim(), StartDate: f.StartDate.value || null, ExpectedSales: f.ExpectedSales.value ? Number(f.ExpectedSales.value) : null, Active: f.Active.checked }; }
function collectTaskFields() { const f = document.getElementById('taskForm'); return { Title: f.Title.value.trim(), Address: f.Address.value.trim(), StartDate: f.StartDate.value || null, EndDate: f.EndDate.value || null, Quantity: f.Quantity.value ? Number(f.Quantity.value) : null, UnitCost: f.UnitCost.value ? Number(f.UnitCost.value) : null, TotalCost: f.TotalCost.value ? Number(f.TotalCost.value) : null, Allocation: f.Allocation.value ? Number(f.Allocation.value) : null, Sprint: f.Sprint.value.trim(), Assignee: f.Assignee.value.trim(), Description: f.Description.value.trim(), Notes: f.Notes.value.trim() }; }
const escapeHtml = s => String(s).replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',''':'&#39;'}[m]));
document.addEventListener('DOMContentLoaded', async () => { document.getElementById('btnSignIn').onclick = async () => { const acct = await login(); if (acct) { showSignedIn(acct); await boot(); } }; document.getElementById('btnSignInCard').onclick = async () => { const acct = await login(); if (acct) { showSignedIn(acct); await boot(); } }; document.getElementById('btnSignOut').onclick = async () => { await logout(); showSignedOut(); }; const acct = await ensureSignedIn(); if (acct) { showSignedIn(acct); await boot(); } else { showSignedOut(); } });
